Filechooser:

<Filechooser>:
	label: label
	orientation: 'vertical'

	FloatLayout:
		FileChooserIconView:
			canvas.before:
				Color:
					rgb: .6, .1, .8
				Rectangle:
					pos: self.pos
					size: root.width,root.height
			on_selection: root.select(*args)

	Button:
		id: label
		size_hint_y: .1
		canvas.before:
			Color:
				rgb: .5, .5, .4
			Rectangle:
				pos: self.pos
				size: self.size

